Внесла данные разработки интерфейса
htmlacademy-javascript/1899553-keksobooking-26 pull request #4
Opened 2022-06-20 16:06 UTC by kuznetsovaleksandra

2022-06-21 08:22 UTC, craz3r requested changes
Нужно вынести все неизменяемые константы (CHECKIN, TYPE, FEATURES, DESCRIPTION, PHOTOS, TITLE) за пределы функции createObject, чтобы не засорять код функции

2022-06-21 08:22 UTC, craz3r commented on js/main.js
> +    avatar: `img / avatars / user${RANDOM_NUMBER === 10 ? RANDOM_NUMBER : ZERO + RANDOM_NUMBER}.png`
Если RANDOM_NUMBER будет больше 10ти, то код сломается

2022-06-21 08:22 UTC, craz3r commented on js/main.js
> +  const ADDRESS = LOCATION;
В чем смысл этой константы, если она просто дублирует LOCATION?

2022-06-21 08:22 UTC, craz3r commented on js/main.js
> +    avatar: `img / avatars / user${RANDOM_NUMBER === 10 ? RANDOM_NUMBER : ZERO + RANDOM_NUMBER}.png`
Нет гарантии, что в твоем коде номер аватара не повторится, тк RANDOM_NUMBER не проверяется на уникальность

2022-06-21 08:22 UTC, craz3r commented on js/main.js
> +const objectsFunc = () => createObjects;
Эта функция здесь по сути лишняя

2022-06-22 06:28 UTC, kuznetsovaleksandra commented on js/main.js
> +    avatar: `img / avatars / user${RANDOM_NUMBER === 10 ? RANDOM_NUMBER : ZERO + RANDOM_NUMBER}.png`
@craz3r у нас же в задание прописано, что число у нас от 1 до 10 и именно в этом диапозоне мы и присваиваем значение. Переписала функцию, чтобы значения не повторялись, но диапозон остался от 1 до 10

2022-06-24 08:55 UTC, merged